app_shop/urls.py
from django.urls import path

from .views import ShopView, AccountView, ProductByCategoryView, ProductView

urlpatterns = [
    path("", ShopView.as_view(), name="main"),
    path("account/", AccountView.as_view(), name="account"),
    path("catalog/", ProductByCategoryView.as_view(), name="catalog"),
    path(
        "catalog/<str:slug>/",
        ProductByCategoryView.as_view(),
        name="product-by-category",
    ),
    path("good/<int:pk>/<str:slug>/", ProductView.as_view(), name="product_detail"),
]

shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_shop.urls")),
    path("cart/", include("app_cart.urls")),
    path("", include("app_users.urls")),
    path("orders/", include("app_orders.urls")),
    path("payment/", include("app_payment.urls")),
    path("api/", include("app_settings.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_orders/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from app_shop.models import Product
from app_users.models import User


class Order(models.Model):
    DELIVERY_CHOICES = (
        ("1", "Обычная доставка"),
        ("2", "Экспресс доставка"),
    )

    PAYMENT_CHOICES = (
        ("1", "Онлайн картой"),
        ("2", "Онлайн со случайного чужого счета"),
    )

    user = models.ForeignKey(
        User,
        related_name="order",
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
    )
    address = models.CharField(max_length=250, verbose_name="Адрес")
    city = models.CharField(max_length=100, verbose_name="Город")
    delivery_type = models.CharField(
        max_length=30,
        choices=DELIVERY_CHOICES,
        verbose_name="Тип доставки",
        default="1",
    )
    delivery_price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Цена доставки", default=0
    )
    payment_type = models.CharField(
        max_length=30, choices=PAYMENT_CHOICES, verbose_name="Тип оплаты", default="1"
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name="создан")
    updated = models.DateTimeField(auto_now=True, verbose_name="изменен")
    paid = models.BooleanField(default=False, verbose_name="оплачен")
    card_number = models.PositiveIntegerField(
        validators=[MinValueValidator(10000000), MaxValueValidator(99999999)],
        verbose_name="Номер карты",
    )
    status = models.CharField(
        max_length=150, verbose_name="статус платежа", blank=True, null=True
    )
    payment_code = models.IntegerField(default=0, verbose_name="Код оплаты")

    class Meta:
        ordering = ("-created",)
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return "Заказ {}".format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all()) + self.delivery_price


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name="items", on_delete=models.CASCADE, verbose_name="заказ"
    )
    product = models.ForeignKey(
        Product,
        related_name="order_items",
        on_delete=models.CASCADE,
        verbose_name="товар",
    )
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="цена")
    quantity = models.PositiveIntegerField(default=1, verbose_name="Количество")

    def __str__(self):
        return "{}".format(self.id)

    def get_cost(self):
        return self.price * self.quantity

    class Meta:
        verbose_name = "Товары"
        verbose_name_plural = "Товары"

app_shop/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Min
from django.urls import reverse
from django.utils.text import slugify
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from .validators import is_svg
from app_settings.models import SiteSettings


def validate_svg(file):
    if not is_svg(file):
        raise ValidationError("Файл не svg")


class Category(MPTTModel):
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, db_index=True, unique=True, verbose_name="Псевдоним для url"
    )
    icon = models.FileField(
        upload_to="category/",
        blank=True,
        validators=[validate_svg],
        verbose_name="Иконка",
    )
    parent = TreeForeignKey(
        "self",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="children",
        db_index=True,
        verbose_name="Родительская категория",
    )
    image = models.ImageField(
        blank=True, upload_to="category/", verbose_name="Изображение"
    )

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        unique_together = [["parent", "slug"]]
        ordering = ("name",)
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("product-by-category", args=[str(self.slug)])

    def get_min(self):
        sub_categories = self.get_descendants(include_self=True)
        price = (
            Product.objects.values("price")
            .filter(category__in=sub_categories)
            .filter(available=True)
            .aggregate(Min("price"))["price__min"]
        )
        return price

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    category = TreeForeignKey(
        "Category",
        on_delete=models.PROTECT,
        related_name="category",
        verbose_name="Категория",
    )
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, db_index=True, verbose_name="Псевдоним для url"
    )
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="Остаток")
    available = models.BooleanField(default=True, verbose_name="Активен")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated = models.DateTimeField(auto_now=True, verbose_name="Обновлен")
    manufacturer = models.CharField(
        max_length=50, db_index=True, verbose_name="Производитель"
    )
    limited = models.BooleanField(default=False, verbose_name="Ограниченная серия")
    option = models.ManyToManyField("PropertyName", through="Property")

    @property
    def in_stock(self):
        return self.stock != 0

    @property
    def total_sale(self):
        return sum(item.quantity for item in self.order_items.all())

    @property
    def total_review(self):
        return len(self.review.all())

    @property
    def free_delivery(self):
        settings = SiteSettings.load()
        return self.price > settings.edge_for_free_delivery

    class Meta:
        ordering = ("price",)
        index_together = (("id", "slug"),)
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("product_detail", args=[self.pk, self.slug])

    def __str__(self):
        return self.name


class PropertyName(models.Model):
    name = models.CharField(
        max_length=255, db_index=True, verbose_name="характеристика"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Имя характеристики"
        verbose_name_plural = "Имена характеристик"


class Property(models.Model):
    property = models.ForeignKey(
        PropertyName,
        on_delete=models.CASCADE,
        related_name="property",
        verbose_name="название",
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name="товар", related_name="property"
    )
    value = models.ForeignKey(
        "PropertyValue",
        on_delete=models.CASCADE,
        verbose_name="значение",
        related_name="property",
    )

    def __str__(self):
        return f"{self.property.name}: {self.value.value}"

    class Meta:
        verbose_name = "Характеристика"
        verbose_name_plural = "Характеристики"


class PropertyValue(models.Model):
    value = models.CharField(max_length=255, verbose_name="значение")

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = "Значение характеристики"
        verbose_name_plural = "Значение характеристик"


class Gallery(models.Model):
    image = models.ImageField(upload_to="products/%Y/%m/%d")
    product = models.ForeignKey(
        "Product",
        on_delete=models.CASCADE,
        related_name="image",
        verbose_name="изображение",
    )

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"

app_shop/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.cache import cache
from django.views import generic
from django.views.generic import DetailView, TemplateView
from django_filters.views import FilterView
from .filters import ProductFilter
from .models import Product, Category
from app_cart.forms import CartAddProductForm
from app_review.forms import ReviewForm
from .utils_shop import get_data_min, get_data_max
from app_settings.models import SiteSettings
from app_review.models import Review


class ShopView(TemplateView):
    template_name = "app_shop/index.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        quantity = SiteSettings.load()
        context["products"] = (
            Product.objects.prefetch_related("order_items")
            .filter(available=True)
            .only("category", "name", "price")
            .annotate(total=Sum("order_items__quantity"))
            .order_by("-total")[: quantity.quantity_popular]
        )
        context["limited"] = (
            Product.objects.select_related("category")
            .filter(available=True)
            .filter(limited=True)
            .only("category", "name", "price")
        )
        return context


class AccountView(LoginRequiredMixin, generic.TemplateView):
    template_name = "app_shop/account.html"
    raise_exception = True


class ProductByCategoryView(FilterView):
    paginate_by = 8
    model = Product
    context_object_name = "products"
    template_name = "app_shop/catalog.html"
    filterset_class = ProductFilter

    def get(self, request, *args, **kwargs):
        self.settings = SiteSettings.load()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        slug = self.kwargs.get("slug")
        if not slug:
            self.category = self.settings.root_category
        else:
            self.category = Category.objects.get(slug=slug)
        sub_categories = self.category.get_descendants(include_self=True)
        queryset = (
            Product.objects.select_related("category")
            .only("name", "price", "category")
            .filter(category__in=sub_categories)
            .filter(available=True)
        )
        return queryset

    def get_context_data(self, **kwargs):
        _request_copy = self.request.GET.copy()
        parameters = _request_copy.pop("page", True) and _request_copy.urlencode()
        context = super().get_context_data(**kwargs)
        context["title"] = self.category
        qs = self.get_queryset()
        min_price = get_data_min(queryset=qs, root_category=self.settings.root_category)
        max_price = get_data_max(queryset=qs, root_category=self.settings.root_category)
        context["parameters"] = parameters
        context["filter"].form.fields["price"].widget.attrs = {
            "class": "range-line",
            "data-type": "double",
            "data-min": min_price,
            "data-max": max_price,
        }
        return context


class ProductView(DetailView):
    model = Product
    template_name = "app_shop/product.html"
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["review_form"] = ReviewForm()
        context["form"] = CartAddProductForm(initial={"quantity": 1})
        context["reviews"] = (
            Review.objects.prefetch_related("user")
            .filter(product=self.get_object())
            .order_by("-created")
        )
        return context

    def get_object(self, queryset=None):
        time_cache = SiteSettings.load().time_cache_product
        if not time_cache:
            time_cache = 1
        return cache.get_or_set(
            f'product:{self.kwargs.get("pk")}',
            Product.objects.get(id=self.kwargs.get("pk")),
            60 * 60 * time_cache,
        )

    def post(self, request, pk, slug):
        form = ReviewForm(request.POST)
        if not request.user.is_authenticated:
            raise PermissionDenied()
        if form.is_valid:
            review = form.save(commit=False)
            review.user = request.user
            review.product = self.get_object()
            review.save()
            messages.success(request, "Отзыв добавлен")
        return HttpResponseRedirect(
            reverse("product_detail", kwargs={"pk": pk, "slug": slug})
        )

app_shop/templates/app_shop/account.html
{% extends "app_shop/base.html" %}
{% load static %}

{% block middle %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Личный кабинет
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{% url 'main' %}">домой</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>Личный кабинет</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">Навигация
                        </strong>
                    </header>
                    <div class="Section-columnContent">
                        <div class="NavigateProfile">
                            <ul class="menu menu_vt">
                                <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'account' %}">Личный
                                    кабинет</a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="{% url 'profile' %}">Профиль</a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="{% url 'history' %}">История заказов</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="Section-content">
                <div class="Account">
                    <div class="Account-group">
                        <div class="Account-column">
                            <div class="Account-avatar">
                                <img src="{% if request.user.avatar %} {{ request.user.avatar.url }} {% else %} {% static 'assets/img/content/home/empty_avatar.jpg' %} {% endif %}" alt="аватар"/>
                            </div>
                        </div>
                        <div class="Account-column">
                            <div class="Account-name">{{ request.user.full_name }}
                            </div>
                            <a class="Account-editLink" href="{% url 'profile' %}">Редактировать профиль</a>
                        </div>
                    </div>
                    {% if request.user.order.first %}
                    {% with order=request.user.order.first %}
                    <div class="Account-group">
                        <div class="Account-column Account-column_full">
                            <div class="Order Order_anons">
                                <div class="Order-personal">
                                    <div class="row">
                                        <div class="row-block"><a class="Order-title"
                                                                  href="{% url 'order_detail' order.id %}">Заказ&#32;<span
                                                class="Order-numberOrder">№{{ order.id }}</span>&#32;от&#32;<span
                                                class="Order-dateOrder">{{ order.created|date:"d.m.Y" }}</span></a>
                                            <div class="Account-editLink"><a href="{% url 'history' %}">История
                                                заказов</a>
                                            </div>
                                        </div>
                                        <div class="row-block">
                                            <div class="Order-info Order-info_delivery">
                                                <div class="Order-infoType">Тип доставки:
                                                </div>
                                                <div class="Order-infoContent">{{ order.get_delivery_type_display }}
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_pay">
                                                <div class="Order-infoType">Оплата:
                                                </div>
                                                <div class="Order-infoContent">{{ order.get_payment_type_display }}
                                                </div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">Общая стоимость:
                                                </div>
                                                <div class="Order-infoContent">{{ order.get_total_cost }} Руб.
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_status">
                                                <div class="Order-infoType">Статус:
                                                </div>
                                                <div class="Order-infoContent">{% if order.paid %} Оплачен {% else %} Не оплачен {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endwith %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

app_shop/templates/app_shop/catalog.html
{% extends "app_shop/base.html" %}
{% load static %}
{% load thumbnail %}


{% block middle %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                {% if title %}
                <h1 class="Middle-title">{{ title }}
                </h1>
                {% else %}
                <h1 class="Middle-title">Каталог Megano
                </h1>
                {% endif %}
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{% url 'main' %}">домой</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>Каталог</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">Фильтр
                        </strong>
                    </header>
                    <div class="Section-columnContent">
                        <form class="form" method="get" id="filter_form">
                            <div class="form-group">
                                <div class="range Section-columnRange">
                                    {{ filter.form.price }}
                                    <div class="range-price">Цена:&#32;
                                        <div class="rangePrice">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                {{ filter.form.name }}
                            </div>
                            <div class="form-group">
                                {{ filter.form.manufacturer }}
                            </div>
                            <div class="form-group">
                                <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->
                            </div>
                            <div class="form-group">
                                <label class="toggle">
                                    {{ filter.form.in_stock }}<span class="toggle-box"></span><span class="toggle-text">Только товары в наличии</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <label class="toggle">
                                    {{ filter.form.delivery }}<span class="toggle-box"></span><span class="toggle-text">С бесплатной доставкой</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <label class="toggle">
                                    {{ filter.form.limited }}<span class="toggle-box"></span><span class="toggle-text">Ограниченная серия</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <div class="buttons">
                                    <button class="btn btn_square btn_dark btn_narrow" type="submit">Применить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="Section-content">
                <div class="Sort">
                    <div class="Sort-title">Сортировать по:
                    </div>
                    <div class="Sort-variants">
                        {{ filter.form.ordering }}
                    </div>
                </div>
                <div class="Cards">
                    {% for card in page_obj %}
                    <div class="Card"><a class="Card-picture" href="{{ card.get_absolute_url }}">
                        <img src="
                        {% thumbnail card.image.first.image '258x172' padding=True as im %}
                        {{ im.url }}
                        {% empty %}
                        {% static 'assets/img/content/home/card.jpg' %}
                        {% endthumbnail %}"
                             alt="товар"/>
                        </a>
                        <div class="Card-content">
                            <strong class="Card-title"><a href="{{ card.get_absolute_url }}">{{ card.name }}</a>
                            </strong>
                            <div class="Card-description">
                                <div class="Card-cost"><span class="Card-price">{{ card.price }} руб.</span>
                                </div>
                                <div class="Card-category">{{ card.category }}
                                </div>
                                <div class="Card-hover">
                                    <form action="{% url 'cart_add' card.id %}" id="form_cart" method="post">
                                        {% csrf_token %}
                                        <a class="Card-btn">
                                            <img src="{% static 'assets/img/icons/cart.svg' %}"
                                                 alt="добавить в корзину"/>
                                        </a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>В данной категории нет товаров</p>
                    {% endfor %}

                </div>
                <div class="Pagination">
                    <div class="Pagination-ins">
                        <a class="Pagination-element Pagination-element_prev"
                           href="?page=1&{{ parameters }}">
                            <img src="{% static 'assets/img/icons/prevPagination.svg'%}" alt="Первая страница"/></a>
                        {% if page_obj.has_previous %}
                        {% with page_num=page_obj.previous_page_number|add:-1 %}
                        {% if page_num > 0 %}
                        <a class="Pagination-element" href="?page={{ page_num }}&{{ parameters }}">
                            <span class="Pagination-text">{{ page_num }}</span></a>
                        {% endif %}
                        {% endwith %}
                        <a class="Pagination-element"
                           href="?page={{ page_obj.previous_page_number }}&{{ parameters }}">
                            <span class="Pagination-text">{{ page_obj.previous_page_number }}</span></a>
                        {% endif %}

                        <a class="Pagination-element Pagination-element_current" href="#">
                            <span class="Pagination-text">{{ page_obj.number }}</span></a>

                        {% if page_obj.has_next %}
                        <a class="Pagination-element" href="?page={{ page_obj.next_page_number }}&{{ parameters }}">
                            <span class="Pagination-text">{{ page_obj.next_page_number }}</span></a>
                        {% with page_num=page_obj.next_page_number|add:1 %}
                        {% if page_num <= page_obj.paginator.num_pages %}
                        <a class="Pagination-element" href="?page={{ page_num }}&{{ parameters }}">
                            <span class="Pagination-text">{{ page_num }}</span></a>
                        {% endif %}
                        {% endwith %}
                        {% endif %}
                        <a class="Pagination-element Pagination-element_prev"
                           href="?page={{ page_obj.paginator.num_pages }}&{{ parameters }}">
                            <img src="{% static 'assets/img/icons/nextPagination.svg'%}" alt="Последняя страница"/></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}